export const TipoCambioProceso = Object.freeze({
    CLOSE_MODAL: 'CLOSE_MODAL',
    OPEN_MODAL_ADD: 'OPEN_MODAL_ADD',
    OPEN_MODAL_EDIT: 'OPEN_MODAL_EDIT',
    ADD_NOTE_ACTION:'ADD_NOTE_ACTION',
    EDIT_NOTE_ACTION:'EDIT_NOTE_ACTION',
    DELETE_NOTE_ACTION:'DELETE_NOTE_ACTION',
    CHANGE_NOTE_ACTION:'CHANGE_NOTE_ACTION'
  })